var problems = [
    "Think rich, look poor.",
    "When you come to a roadblock, take a detour.",
    "Be quick, but don't hurry.",
    "When it is dark enough, you can see the stars.",
    "Never let your memories be greater than your dreams.",
    "A problem is a chance for you to do your best.",
    "Victory is sweetest when you've known defeat.",
    "One of these days is none of these days.",
    "Believe and act as if it were impossible to fail.",
    "If you obey all the rules, you miss all the fun.",
    "A wise man will make more opportunities than he finds.",
    "People do not lack strength, they lack will.",
    "I have a dream today!",
    "There is always light behind the clouds.",
    "Vision is the art of seeing things invisible.",
]
var initProblems = [
    "Think rich, look poor.",
    "When you come to a roadblock, take a detour.",
    "Be quick, but don't hurry.",
    "When it is dark enough, you can see the stars.",
    "Never let your memories be greater than your dreams.",
    "A problem is a chance for you to do your best.",
    "Victory is sweetest when you've known defeat.",
    "One of these days is none of these days.",
    "Believe and act as if it were impossible to fail.",
    "If you obey all the rules, you miss all the fun.",
    "A wise man will make more opportunities than he finds.",
    "People do not lack strength, they lack will.",
    "I have a dream today!",
    "There is always light behind the clouds.",
    "Vision is the art of seeing things invisible.",
]